baseURL: https://www.olivermking.com/
languageCode: en-us
title: OliverMKing
theme: PaperMod

params:
  defaultTheme: auto # switch between dark or light according to browser theme

  homeInfoParams:
    Title: Hi there 👋
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: https://github.com/OliverMKing
    - name: linkedin
      url: https://www.linkedin.com/in/oliver-merkley-king/

  showShareButtons: true
